/* ═══════════════════════════════════════════════════════
   WITHOUT A CLASP — Price Data
   Managed via admin.html — do not edit this file directly.
   ═══════════════════════════════════════════════════════ */

var WAC_PRICES = {

  cards: [
    {
      id: "bracelets",
      title: "Bracelets",
      icon: "bracelet",
      rows: [
        { name: "Fine Chain Bracelet", material: "Sterling Silver", price: "55",  poa: false },
        { name: "Fine Chain Bracelet", material: "Gold Fill",        price: "65",  poa: false },
        { name: "Fine Chain Bracelet", material: "14k Solid Gold",   price: "120", poa: false }
      ]
    },
    {
      id: "anklets",
      title: "Anklets",
      icon: "anklet",
      rows: [
        { name: "Fine Chain Anklet", material: "Sterling Silver", price: "60",  poa: false },
        { name: "Fine Chain Anklet", material: "Gold Fill",       price: "70",  poa: false },
        { name: "Fine Chain Anklet", material: "14k Solid Gold",  price: "130", poa: false }
      ]
    },
    {
      id: "necklaces",
      title: "Necklaces",
      icon: "necklace",
      rows: [
        { name: "Fine Chain Necklace", material: "Sterling Silver", price: "65",  poa: false },
        { name: "Fine Chain Necklace", material: "Gold Fill",       price: "75",  poa: false },
        { name: "Fine Chain Necklace", material: "14k Solid Gold",  price: "145", poa: false }
      ]
    },
    {
      id: "rings",
      title: "Rings",
      icon: "ring",
      rows: [
        { name: "Permanent Ring", material: "Sterling Silver",                 price: "50", poa: false },
        { name: "Permanent Ring", material: "Gold Fill",                       price: "60", poa: false },
        { name: "Permanent Ring", material: "14k Solid Gold — please enquire", price: "",   poa: true  }
      ]
    }
  ],

  addons: [
    { name: "Star Charm",  icon: "star",  price: "from £15",     desc: "Delicate charm additions, welded permanently alongside your chain." },
    { name: "Heart Charm", icon: "heart", price: "from £15",     desc: "A classic, meaningful addition — perfect for gifting." },
    { name: "Birthstone",  icon: "stone", price: "from £22",     desc: "Fine stone settings in select styles. Enquire for options." },
    { name: "Re-Weld",     icon: "weld",  price: "Reduced Rate", desc: "If your piece ever releases, I'll re-weld it at a preferential rate." }
  ]

};
